apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}
  labels:
    app: {{ include "mssql.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.mssql.service.labels }}
{{ toYaml .Values.mssql.service.labels | indent 4 }}
{{- end }}
{{- if .Values.mssql.service.annotations }}
  annotations:
{{ toYaml .Values.mssql.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ include "mssql.fullname" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.mssql.service.port }}
      targetPort: {{ .Chart.Name }}
