USE [master];
GO

DROP DATABASE IF EXISTS [development];
GO

IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'app_user' AND type = 'S')
BEGIN
    DROP LOGIN app_user;
END

CREATE DATABASE [development] collate SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [development] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [development].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [development] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [development] SET ANSI_NULLS OFF
GO
ALTER DATABASE [development] SET ANSI_PADDING OFF
GO
ALTER DATABASE [development] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [development] SET ARITHABORT OFF
GO
ALTER DATABASE [development] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [development] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [development] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [development] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [development] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [development] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [development] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [development] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [development] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [development] SET  DISABLE_BROKER
GO
ALTER DATABASE [development] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [development] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [development] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [development] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [development] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [development] SET RECOVERY FULL
GO
ALTER DATABASE [development] SET  MULTI_USER
GO
ALTER DATABASE [development] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [development] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [development] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [development] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [development] SET QUERY_STORE = OFF
GO

--- Create logins

USE [master];
GO

-- Create an admin login
CREATE LOGIN [db_admin_test_user] WITH PASSWORD = 'admin$Pass';
GO

-- Create an application login
CREATE LOGIN [db_exchange_test_user] WITH PASSWORD = 'user$Pass';
GO

--- Create users

USE [development];
GO

CREATE LOGIN app_user WITH PASSWORD = 'appuser$Pass';
GO

CREATE USER [app_user] FOR LOGIN [app_user] WITH DEFAULT_SCHEMA=[dbo];
GO