apiVersion: v1
kind: Service
metadata:
    name: mongo-nodeport-svc
    labels:
        app: mongo
spec:
    type: LoadBalancer
    ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
          nodePort: 32000
    selector:
        app: mongo
  

