version: "3.7"
services:

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "0o0*5YMI4Ts"
      MSSQL_RPC_PORT: 135
      MSSQL_PID: Developer
    labels:
      - "vendor=Microsoft"