apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-mssql-helm-chart.fullname" . }}-mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.persistence.storageSize }}
