apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-mssql-helm-chart.fullname" . }}-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-mssql-helm-chart.name" . }}-mssql
  template:
    metadata:
      labels:
        app: {{ include "my-mssql-helm-chart.name" . }}-mssql
    spec:
      containers:
        - name: mssql
          image: "{{ .Values.mssql.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1443
              protocol: TCP
          volumeMounts:
            - name: mssql-data
              mountPath: {{ .Values.mssql.persistence.mountPath }}
          envFrom:
            - configMapRef:
                name: {{ include "my-mssql-helm-chart.fullname" . }}-mssql-config
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-mssql-helm-chart.fullname" . }}-mssql-secret
                  key: sa-password
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - {{ .Values.mssql.healthcheck.test }}
            initialDelaySeconds: {{ .Values.mssql.healthcheck.startPeriod }}
            periodSeconds: {{ .Values.mssql.healthcheck.interval }}
            timeoutSeconds: {{ .Values.mssql.healthcheck.timeout }}
            failureThreshold: {{ .Values.mssql.healthcheck.retries }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - {{ .Values.mssql.healthcheck.test }}
            initialDelaySeconds: {{ .Values.mssql.healthcheck.startPeriod }}
            periodSeconds: {{ .Values.mssql.healthcheck.interval }}
            timeoutSeconds: {{ .Values.mssql.healthcheck.timeout }}
            failureThreshold: {{ .Values.mssql.healthcheck.retries }}
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: {{ include "my-mssql-helm-chart.fullname" . }}-mssql-pvc