{{- if and .Values.mssql.persistence.enabled (not .Values.mssql.persistence.existingDataClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql.fullname" . }}-data
  labels:
    app: {{ include "mssql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.mssql.persistence.annotations }}
  annotations:
{{ toYaml .Values.mssql.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.mssql.persistence.dataAccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mssql.persistence.dataSize | quote }}
{{- if .Values.mssql.persistence.storageClass }}
{{- if (eq "-" .Values.mssql.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.mssql.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
