apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mssql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mssql.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mssql.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.mssql.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "mssql.fullname" . }}-data
              mountPath: {{ .Values.mssql.persistence.mountPath }}
          envFrom:
            - configMapRef:
                name: {{ include "mssql.fullname" . }}-config
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -Q 'SELECT 1'

            initialDelaySeconds: {{ .Values.mssql.healthcheck.startPeriod }}
            periodSeconds: {{ .Values.mssql.healthcheck.interval }}
            timeoutSeconds: {{ .Values.mssql.healthcheck.timeout }}
            failureThreshold: {{ .Values.mssql.healthcheck.retries }}
      volumes:
        - name: {{ include "mssql.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "mssql.fullname" . }}-data