apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-mssql-helm-chart.fullname" . }}-mssql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mssql.ports.servicePort }}
      targetPort: {{ .Values.mssql.ports.containerPort }}
      protocol: TCP
      name: mssql
  selector:
    app: {{ include "my-mssql-helm-chart.name" . }}-mssql