apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mssql.fullname" . }}-sqlcmd
spec:
  template:
    spec:
      activeDeadlineSeconds: 90
      containers:
        - name: sqlcmd
          image: "{{ .Values.sqlcmd.image }}"
          command: ["/bin/bash", "-c", "{{ .Values.sqlcmd.mountPath }}/{{ .Values.sqlcmd.scriptName }}"]
          volumeMounts:
            - name: migration-scripts
              mountPath: {{ .Values.sqlcmd.mountPath }}
          envFrom:
            - configMapRef:
                name: {{ include "mssql.fullname" . }}-config
      restartPolicy: Never
      volumes:
        - name: migration-scripts
          hostPath:
            path: {{ .Values.sqlcmd.hostPath }}
            type: Directory
  backoffLimit: 10