services:
    mysql:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: db
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend
        restart: unless-stopped

volumes:
    mysql_data:

networks:
    backend:
        external: true