.PHONY: install uninstall password

password: ## Prints password
	@kubectl get secret --namespace redis redis -o jsonpath="{.data.redis-password}" | base64 -d

install: ## Installs helm chart
	@helm install redis bitnami/redis --create-namespace --namespace redis -f values.yaml

uninstall: ## Uninstalls helm chart
	@helm uninstall redis -n redis

# Helper rules

.PHONY: list
list: ## List all make targets
	@${MAKE} -pRrn : -f $(MAKEFILE_LIST) 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | egrep -v -e '^[^[:alnum:]]' -e '^$@$$' | sort

.PHONY: help
.DEFAULT_GOAL := help
help:
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

# Variable outputting/exporting rules
var-%: ; @echo $($*)
varexport-%: ; @echo $*=$($*)